# Prespecified descriptive ORA/GSEA concordance; unique stable GO identifiers.
suppressPackageStartupMessages({library(dplyr);library(GO.db);library(AnnotationDbi)})
mass<-readxl::read_excel('Outputs/Supplementary_Data.xlsx',sheet='Viral_pathway_tests')
earli<-readxl::read_excel('Outputs/Supplementary_Data.xlsx',sheet='EARLI_viral_GSEA')
normalize<-function(x)paste0('GOBP_',gsub('^_|_$','',gsub('[^A-Z0-9]+','_',toupper(x))))
ann<-AnnotationDbi::select(GO.db,keys=keys(GO.db,keytype='GOID'),columns=c('TERM','ONTOLOGY'),keytype='GOID') %>% filter(ONTOLOGY=='BP') %>% transmute(ID=GOID,TERM,pathway=normalize(TERM)) %>% distinct()
map<-ann %>% group_by(pathway) %>% mutate(Mapping_n=n_distinct(ID)) %>% ungroup()
write.csv(map,'Outputs/EARLI_GO_annotation_mapping.csv',row.names=FALSE)
e<-earli %>% mutate(Virus=recode(Pathogen,HHV5='HCMV',HHV4='EBV')) %>% left_join(map,by='pathway',relationship='many-to-many')
write.csv(e %>% filter(is.na(ID)|Mapping_n!=1),'Outputs/EARLI_unmatched_ambiguous_GO.csv',row.names=FALSE)
e<-e %>% filter(!is.na(ID),Mapping_n==1,padj<.05) %>% dplyr::select(Virus,ID,pathway,NES,padj) %>% distinct()
stopifnot(!anyDuplicated(e[c('Virus','ID')]))
m<-mass %>% filter(p.adjust<.05,qvalue<.05) %>% group_by(Virus,ID) %>% summarise(MASS_direction=paste(sort(unique(Direction)),collapse=';'),MASS_FDR=min(p.adjust),MASS_qvalue=min(qvalue),.groups='drop')
z<-inner_join(m,e,by=c('Virus','ID')) %>% mutate(Category=case_when(grepl(';',MASS_direction)~'MASS bidirectional', (MASS_direction=='Up')==(NES>0)~'Concordant',TRUE~'Discordant'))
stopifnot(!anyDuplicated(z[c('Virus','ID')]))
write.csv(z,'Outputs/Figure4D_GO_concordance.csv',row.names=FALSE)
summary<-z %>% count(Virus,Category) %>% group_by(Virus) %>% mutate(Unique_overlap=sum(n),Directional_denominator=sum(n[Category!='MASS bidirectional'])) %>% ungroup()
write.csv(summary,'Outputs/Figure4D_GO_concordance_summary.csv',row.names=FALSE)
writeLines(c('MASS ORA: p.adjust <0.05 AND qvalue <0.05; EARLI GSEA: padj <0.05.',paste('GO.db',packageVersion('GO.db')),'GO IDs mapped by unique normalized current BP annotation term; no fuzzy or forced match.','Bidirectional MASS enrichments excluded from directional denominator, retained in unique overlap.','Original 119/119 and 49/57 selection rules were not recovered.'),'Outputs/Figure4D_concordance_rules.txt')
print(summary)
