# Run from the repository root. Panel sources are in manifest.csv.
source("code/shared_paths.R")
source("code/shared_CMAISE_visit_rules.R")
invisible(NULL)

options(stringsAsFactors = FALSE)

suppressPackageStartupMessages({
    library(dplyr)
    library(tidyr)
    library(glmnet)
    library(pROC)
    library(ggplot2)
})

project_dir <- "."

input_file <- repo_path(project_dir, "Inputs/260827_SRR_meta_model.rdata")

classification_file <- repo_path(project_dir, "Inputs/260830_SRR_CTS_classification.csv")

output_dir <- repo_path(project_dir, "Outputs")

repo_dir(output_dir, recursive = TRUE, showWarnings = FALSE)

prefix <- repo_path(output_dir, "260830_SRR_CTS_nestedCV")

base_seed <- 260830L

n_repeats <- 20L

n_outer_folds <- 5L

n_inner_folds <- 5L

timepoints <- c("D3", "D5")

cts_genes <- c("SLC4A1", "SERPINB1", "FECH", "ACER3", "NLRC4", "BTN3A3", "SNX3", "GADD45A", "CA1", "PGD", 
    "STOM", "TDRD9", "HK3", "EPB42", "BPGM", "GLRX5", "UBE2H", "METTL9")

if (!repo_exists(input_file)) stop("Missing input: ", input_file)

if (!repo_exists(classification_file)) {
    stop("Missing CTS classification generated by FigureS11D_plot.R: ", classification_file)
}

input_env <- new.env(parent = emptyenv())

load(repo_input(input_file), envir = input_env)

stopifnot(exists("meta_model", input_env))

meta_model <- input_env$meta_model

cts_class <- read.csv(repo_input(classification_file), check.names = FALSE)

if (anyDuplicated(meta_model$HumanID)) stop("meta_model HumanID is not unique")

if (!all(c("HumanID", "Timepoint", "CTS") %in% names(cts_class))) stop("Invalid CTS classification file")

if (anyDuplicated(cts_class[c("HumanID", "Timepoint")])) stop("Duplicated patient/timepoint CTS classification")

make_stratified_folds <- function(y, k, seed) {
    set.seed(seed)
    fold <- integer(length(y))
    for (event in sort(unique(y))) {
        idx <- sample(which(y == event))
        fold[idx] <- rep(seq_len(k), length.out = length(idx))
    }
    if (any(tabulate(fold, nbins = k) == 0L)) 
        stop("An empty fold was created")
    if (any(vapply(seq_len(k), function(i) length(unique(y[fold == i])), integer(1)) < 2L)) {
        stop("At least one stratified fold lacks an outcome class")
    }
    fold
}

calc_auc <- function(y, probability) {
    as.numeric(pROC::auc(pROC::roc(y, probability, levels = c(0, 1), direction = "<", quiet = TRUE)))
}

safe_logistic_prediction <- function(formula, train, test) {
    fit <- suppressWarnings(glm(formula, data = train, family = binomial()))
    probability <- suppressWarnings(as.numeric(predict(fit, newdata = test, type = "response")))
    if (any(!is.finite(probability))) 
        stop("Non-finite logistic held-out probability")
    pmin(pmax(probability, 1e-08), 1 - 1e-08)
}

fit_nested_m1 <- function(train, test, sofa_var, gene_vars, inner_seed) {
    features <- c(sofa_var, gene_vars)
    x_train <- as.matrix(train[, features, drop = FALSE])
    x_test <- as.matrix(test[, features, drop = FALSE])
    inner_foldid <- make_stratified_folds(train$Mortality28d, n_inner_folds, inner_seed)
    fit <- cv.glmnet(x_train, train$Mortality28d, family = "binomial", alpha = 0.5, lambda = NULL, type.measure = "deviance", 
        nfolds = n_inner_folds, foldid = inner_foldid, penalty.factor = c(0, rep(1, length(gene_vars))), 
        standardize = TRUE, intercept = TRUE)
    coefficients <- as.matrix(coef(fit, s = "lambda.min"))[, 1]
    probability <- as.numeric(predict(fit, newx = x_test, s = "lambda.min", type = "response"))
    if (any(!is.finite(probability))) 
        stop("Non-finite elastic-net held-out probability")
    list(probability = pmin(pmax(probability, 1e-08), 1 - 1e-08), lambda_min = fit$lambda.min, selected_CTS_n = sum(coefficients[gene_vars] != 
        0))
}

prepare_timepoint <- function(tp) {
    sofa_var <- paste0("SOFA_", tp)
    gene_vars <- paste0(tp, "_CTSg_", cts_genes)
    required <- c("HumanID", "Mortality28d", sofa_var, gene_vars)
    missing <- setdiff(required, names(meta_model))
    if (length(missing)) 
        stop(tp, " missing variables: ", paste(missing, collapse = ", "))
    subtype <- cts_class %>% filter(Timepoint == tp) %>% dplyr::select(HumanID, CTS)
    cohort <- meta_model %>% dplyr::select(all_of(required)) %>% inner_join(subtype, by = "HumanID") %>% 
        filter(if_all(everything(), ~!is.na(.x))) %>% mutate(Mortality28d = as.integer(Mortality28d), 
        across(all_of(c(sofa_var, gene_vars)), as.numeric), CTS = factor(CTS, levels = c("CTS1", "CTS2", 
            "CTS3"))) %>% arrange(HumanID)
    cohort <- cohort %>% filter(cmaise_keep_visit(HumanID,tp))
    if (!identical(sort(unique(cohort$Mortality28d)), c(0L, 1L))) 
        stop(tp, " outcome is not 0/1")
    if (any(!is.finite(as.matrix(cohort[, c(sofa_var, gene_vars)])))) 
        stop(tp, " has non-finite predictors")
    if (any(vapply(cohort[gene_vars], sd, numeric(1)) == 0)) 
        stop(tp, " has a zero-variance CTS gene")
    if (any(table(cohort$CTS) == 0L)) 
        stop(tp, " lacks a CTS subtype")
    list(data = cohort, sofa = sofa_var, genes = gene_vars)
}

model_definitions <- tibble(Model=c("M0","M1"),
  Display=c("Contemporaneous SOFA","SOFA + 18 CTS genes"),
  Algorithm=c("Logistic regression","Elastic net logistic regression"),
  Specification=c("contemporaneous SOFA","contemporaneous SOFA (unpenalized) + 18 CTS genes (penalized); alpha=0.5; nested lambda.min"))

cohort_list <- setNames(lapply(timepoints, prepare_timepoint), timepoints)

oof_predictions <- bind_rows(lapply(seq_along(timepoints), function(tp_i) {
    tp <- timepoints[tp_i]
    if(tp=="D5") {
      old<-read.csv("Inputs/FigureS11E_oof_predictions.csv")
      old<-old[old$Timepoint==tp,]
      stopifnot(setequal(old$HumanID,cohort_list[[tp]]$data$HumanID))
      return(old)
    }
    message("Refitting affected CMAISE ",tp)
    cohort <- cohort_list[[tp]]$data
    sofa_var <- cohort_list[[tp]]$sofa
    gene_vars <- cohort_list[[tp]]$genes
    bind_rows(lapply(seq_len(n_repeats), function(repeat_id) {
        outer_fold <- make_stratified_folds(cohort$Mortality28d, n_outer_folds, base_seed + tp_i * 100000L + 
            repeat_id * 1000L)
        repeat_data <- cohort %>% mutate(Outer_fold = outer_fold)
        bind_rows(lapply(seq_len(n_outer_folds), function(fold_id) {
            train <- repeat_data %>% filter(Outer_fold != fold_id)
            test <- repeat_data %>% filter(Outer_fold == fold_id)
            m0_probability <- safe_logistic_prediction(reformulate(sofa_var, response = "Mortality28d"), 
                train, test)
            m1 <- fit_nested_m1(train, test, sofa_var, gene_vars, base_seed + tp_i * 1000000L + repeat_id * 
                100L + fold_id)
            tibble(Timepoint = tp, HumanID = test$HumanID, Mortality28d = test$Mortality28d, CTS = as.character(test$CTS), 
                Repeat = repeat_id, Outer_fold = fold_id, M0_probability = m0_probability, M1_probability = m1$probability, 
                M1_lambda_min = m1$lambda_min, M1_selected_CTS_n = m1$selected_CTS_n)
        }))
    }))
})) %>% arrange(Timepoint, Repeat, Outer_fold, HumanID)

for (tp in timepoints) {
    z <- oof_predictions %>% filter(Timepoint == tp)
    expected_n <- nrow(cohort_list[[tp]]$data) * n_repeats
    if (nrow(z) != expected_n || any(count(z, Repeat, HumanID)$n != 1L)) 
        stop(tp, " OOF completeness failure")
    if (any(!is.finite(as.matrix(z[, grep("_probability$", names(z))])))) 
        stop(tp, " invalid OOF probability")
    fold_check <- z %>% distinct(Repeat, Outer_fold, Mortality28d) %>% count(Repeat, Outer_fold)
    if (any(fold_check$n != 2L)) 
        stop(tp, " outer fold lost outcome stratification")
}

write.csv(oof_predictions, repo_output(paste0(prefix, "_oof_predictions.csv"), "FigureS11E_analysis.R"), 
    row.names = FALSE)

repeat_performance <- oof_predictions %>% pivot_longer(matches("^M[012]_probability$"), names_to = "Model", 
    values_to = "Probability") %>% mutate(Model = sub("_probability$", "", Model)) %>% group_by(Timepoint, 
    Repeat, Model) %>% summarise(AUC = calc_auc(Mortality28d, Probability), Brier = mean((Mortality28d - 
    Probability)^2), .groups = "drop")

cohort_counts <- bind_rows(lapply(timepoints, function(tp) {
    x <- cohort_list[[tp]]$data
    tibble(Timepoint = tp, N = nrow(x), Deaths = sum(x$Mortality28d == 1L), Survivors = sum(x$Mortality28d == 
        0L))
}))

performance <- repeat_performance %>% group_by(Timepoint, Model) %>% summarise(Repeats = n(), Mean_AUC = mean(AUC), 
    AUC_Q25 = quantile(AUC, 0.25), AUC_Q75 = quantile(AUC, 0.75), AUC_IQR = IQR(AUC), Mean_Brier = mean(Brier), 
    Brier_Q25 = quantile(Brier, 0.25), Brier_Q75 = quantile(Brier, 0.75), Brier_IQR = IQR(Brier), .groups = "drop") %>% 
    left_join(cohort_counts, by = "Timepoint") %>% left_join(model_definitions, by = "Model") %>% dplyr::select(Timepoint, 
    Model, Display, Specification, Algorithm, N, Deaths, Survivors, everything())

write.csv(repeat_performance,"Outputs/FigureS11E_repeat_performance.csv",row.names=FALSE)
write.csv(performance, repo_output(paste0(prefix, "_performance.csv"), "FigureS11E_analysis.R"), 
    row.names = FALSE)

contrast_definitions <- tibble(Contrast = "M1 - M0", New_model = "M1", Reference_model = "M0")

contrast_distributions <- bind_rows(lapply(seq_len(nrow(contrast_definitions)), function(i) {
    def <- contrast_definitions[i, ]
    w <- repeat_performance %>% filter(Model %in% c(def$New_model, def$Reference_model)) %>% pivot_wider(names_from = Model, 
        values_from = c(AUC, Brier))
    tibble(Timepoint = w$Timepoint, Repeat = w$Repeat, Contrast = def$Contrast, New_model = def$New_model, 
        Reference_model = def$Reference_model, DeltaAUC = w[[paste0("AUC_", def$New_model)]] - w[[paste0("AUC_", 
            def$Reference_model)]], DeltaBrier = w[[paste0("Brier_", def$New_model)]] - w[[paste0("Brier_", 
            def$Reference_model)]])
}))

mean_ci <- function(x) {
    m <- mean(x)
    se <- sd(x)/sqrt(length(x))
    crit <- qt(0.975, length(x) - 1L)
    c(lower = m - crit * se, upper = m + crit * se)
}

contrasts <- contrast_distributions %>% group_by(Timepoint, Contrast, New_model, Reference_model) %>% 
    summarise(Repeats = n(), Mean_DeltaAUC = mean(DeltaAUC), DeltaAUC_Q25 = quantile(DeltaAUC, 0.25), 
        DeltaAUC_Q75 = quantile(DeltaAUC, 0.75), DeltaAUC_IQR = IQR(DeltaAUC), DeltaAUC_repeat_SE = sd(DeltaAUC)/sqrt(n()), 
        Mean_DeltaBrier = mean(DeltaBrier), DeltaBrier_Q25 = quantile(DeltaBrier, 0.25), DeltaBrier_Q75 = quantile(DeltaBrier, 
            0.75), DeltaBrier_IQR = IQR(DeltaBrier), DeltaBrier_repeat_SE = sd(DeltaBrier)/sqrt(n()), 
        Delta_definition = "new minus M0; positive DeltaAUC and negative DeltaBrier favor new model", 
        .groups = "drop")

write.csv(contrasts, repo_output(paste0(prefix, "_contrasts.csv"), "FigureS11E_analysis.R"), row.names = FALSE)

common_theme <- theme_classic(base_size = 11) + theme(legend.position = "none", plot.margin = margin(8, 
    15, 22, 8))

plot_m01_data <- repeat_performance %>% filter(Model %in% c("M0", "M1")) %>% mutate(Timepoint = factor(Timepoint, 
    c("D3", "D5")), x = match(Model, c("M0", "M1")))

panel_m01_scale <- plot_m01_data %>% group_by(Timepoint) %>% summarise(Q25 = quantile(AUC, 0.25), Q75 = quantile(AUC, 
    0.75), Panel_IQR = max(Q75 - Q25, 0.005), Data_min = min(AUC), Data_max = max(AUC), Y_lower = Data_min - 
    0.6 * Panel_IQR, Bracket_y = Data_max + 1.9 * Panel_IQR, Bracket_tick = 0.25 * Panel_IQR, Bracket_label_y = Bracket_y + 
    0.2 * Panel_IQR, Y_upper = Bracket_label_y + 1 * Panel_IQR, .groups = "drop")

panel_m01_anchors <- panel_m01_scale %>% select(Timepoint, Y_lower, Y_upper) %>% pivot_longer(c(Y_lower, 
    Y_upper), names_to = "Anchor", values_to = "AUC")

mean_m01_plot <- plot_m01_data %>% group_by(Timepoint, Model, x) %>% summarise(Max_AUC = max(AUC), AUC = mean(AUC), 
    .groups = "drop") %>% mutate(Mean_label_y = Max_AUC + 0.0025)

delta_m01_labels <- contrasts %>% filter(Contrast == "M1 - M0") %>% mutate(Timepoint = factor(Timepoint, 
    c("D3", "D5")), x = 1, xend = 2, label = sprintf("AUC %+.3f", Mean_DeltaAUC)) %>% left_join(panel_m01_scale %>% 
    select(Timepoint, Bracket_y, Bracket_tick, Bracket_label_y), by = "Timepoint")

p_auc_m01 <- ggplot(plot_m01_data, aes(x = x, y = AUC, group = interaction(Timepoint, Model), color = Model)) + 
    geom_boxplot(aes(fill = Model), width = 0.32, outlier.shape = NA, alpha = 0.22, linewidth = 0.65, 
        color = "grey25") + geom_jitter(size = 1.7, alpha = 0.55, position = position_jitter(width = 0.085, 
    height = 0, seed = 260830)) + geom_blank(data = panel_m01_anchors, aes(x = 1.5, y = AUC), inherit.aes = FALSE) + 
    geom_point(data = mean_m01_plot, aes(x = x, y = AUC, fill = Model), inherit.aes = FALSE, shape = 23, 
        size = 4.3, stroke = 0.8, color = "black") + geom_text(data = mean_m01_plot, aes(x = x, y = Mean_label_y, 
    label = sprintf("%.3f", AUC)), inherit.aes = FALSE, size = 3.5, fontface = "bold") + geom_segment(data = delta_m01_labels, 
    aes(x = x, xend = xend, y = Bracket_y, yend = Bracket_y), inherit.aes = FALSE, linewidth = 0.6, color = "#285A84") + 
    geom_segment(data = delta_m01_labels, aes(x = x, xend = x, y = Bracket_y - Bracket_tick, yend = Bracket_y), 
        inherit.aes = FALSE, linewidth = 0.6, color = "#285A84") + geom_segment(data = delta_m01_labels, 
    aes(x = xend, xend = xend, y = Bracket_y - Bracket_tick, yend = Bracket_y), inherit.aes = FALSE, 
    linewidth = 0.6, color = "#285A84") + geom_text(data = delta_m01_labels, aes(x = (x + xend)/2, y = Bracket_label_y, 
    label = label), inherit.aes = FALSE, size = 3.1, vjust = 0, color = "#285A84", lineheight = 0.95) + 
    facet_wrap(~Timepoint, nrow = 1, scales = "free_y", labeller = as_labeller(c(D3 = "CMAISE Day 3", 
        D5 = "CMAISE Day 5"))) + scale_x_continuous(breaks = c(1, 2), labels = c("SOFA", "SOFA +\nCTS genes"), 
    limits = c(0.45, 2.55), expand = c(0, 0)) + scale_y_continuous(breaks = function(x) pretty(x, n = 4), 
    expand = c(0, 0)) + scale_color_manual(values = c(M0 = "#7F7F7F", M1 = "#4575B4")) + scale_fill_manual(values = c(M0 = "#7F7F7F", 
    M1 = "#4575B4")) + labs(x = NULL, y = "Outer-CV AUC", title = "CTS gene prediction in CMAISE", subtitle = "20 repeats x stratified 5-fold outer CV", 
    caption = "Small points are repeat-level AUCs; boxes show median and IQR;\ndiamonds show means.") + 
    common_theme + theme(plot.title = element_text(face = "bold", hjust = 0.5, size = 14), plot.subtitle = element_text(hjust = 0.5, 
    size = 10.5), strip.text = element_text(face = "bold"), plot.caption = element_text(size = 8.5))

ggsave(repo_output(paste0(prefix, "_AUC_M0_M1.pdf"), "FigureS11E_analysis.R"), p_auc_m01, width = 5, 
    height = 3.3)

